package adris.altoclef.mixins;

import net.minecraft.client.gui.screen.world.SelectWorldScreen;
import org.spongepowered.asm.mixin.Mixin;
//#if MC <= 11601
//$$ import adris.altoclef.Debug;
//$$ import adris.altoclef.Settings;
//$$ import net.minecraft.client.MinecraftClient;
//$$ import net.minecraft.client.gui.screen.world.WorldListWidget;
//$$ import org.spongepowered.asm.mixin.Unique;
//$$ import org.spongepowered.asm.mixin.injection.At;
//$$ import org.spongepowered.asm.mixin.injection.Inject;
//$$ import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
//$$
//$$ import java.util.List;
//#endif

/**
 * Headless auto-world loader for the SIM harness.
 *
 * <p>Why this exists: the SIM box runs without an interactive desktop, so
 * {@code SetForegroundWindow} returns 0 and the PowerShell SendKeys create-world
 * automation can never focus the game (see docs/SIM_HARNESS.md, blocker
 * {@code need_ui_focus}). This mixin replaces that UI automation with an in-process
 * path: when {@code autoLoadWorld} is true in {@code altoclef_settings.json}, the
 * world list screen immediately plays the first save.
 *
 * <p>Safety, matching the harness rules:
 * <ul>
 *   <li>Never creates a world here — only loads an existing save, so no Hardcore
 *       world can be generated by this code path.</li>
 *   <li>Fires once per JVM; further world rotation is left to the harness loop.</li>
 *   <li>Selection is positional (first row of a stable, pre-pruned list), not
 *       name-based, so it cannot drift to a different world on a rename.</li>
 * </ul>
 *
 * <p>1.16.1 specifics: there is no
 * {@code SelectWorldScreen.play(LevelSummary, boolean)} on this version. The rows are
 * {@code WorldListWidget$Entry} (which owns {@code play()}), reached through
 * {@code EntryListWidget.children()}. Selecting the row before playing matches what a
 * click does, so the screen's own selection-dependent buttons stay consistent.
 */
@Mixin(SelectWorldScreen.class)
public class AutoWorldLoadMixin {
    //#if MC <= 11601
    //$$
    //$$ @Unique
    //$$ private static boolean _altoAutoWorldPickDone = false;
    //$$
    //$$ @Inject(at = @At("TAIL"), method = "init()V")
    //$$ private void altoAutoPickWorld(CallbackInfo info) {
    //$$     if (_altoAutoWorldPickDone || !Settings.isAutoLoadWorldEnabled()) {
    //$$         return;
    //$$     }
    //$$     SelectWorldScreen self = (SelectWorldScreen) (Object) this;
    //$$     WorldListWidget list = ((SelectWorldScreenAccessor) self).altoGetLevelList();
    //$$     if (list == null) {
    //$$         Debug.logMessage("AUTOWORLD: levelList null — cannot auto-load");
    //$$         return;
    //$$     }
    //$$     List<WorldListWidget.Entry> rows =
    //$$             list.children();
    //$$     if (rows == null || rows.isEmpty()) {
    //$$         Debug.logMessage("AUTOWORLD: no saves in saves/ — create one first");
    //$$         return;
    //$$     }
    //$$
    //$$     WorldListWidget.Entry pick = rows.get(0);
    //$$     _altoAutoWorldPickDone = true;
    //$$     Debug.logMessage("AUTOWORLD: headless play -> row[0] of " + rows.size() + " save(s)");
    //$$
    //$$     MinecraftClient client = MinecraftClient.getInstance();
    //$$     if (client != null && client.currentScreen instanceof SelectWorldScreen) {
    //$$         client.openScreen(null);
    //$$     }
    //$$     list.setSelected(pick);
    //$$     pick.play();
    //$$ }
    //#endif
}
